spring.application.name=authservice

# Cấu hình kết nối MySQL (Lấy tài khoản mật khẩu từ biến môi trường)
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/tramthuc?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Cấu hình kết nối Redis Cloud
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# Khai báo Secret Key cho JWT (để test ở máy Local, khi lên mạng sẽ bị đè bằng biến thật)
jwt.secret.key=NDQ1MzU1NjU1MzY4NTY2RDU5NzEzMzczMzY3NjM5NzkyNDQyMjY0NTI5NDg0MDRENjM1MTY1NTQ2ODU3NkQ1QQ==

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true